<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="1" failures="1" tests="3" name="tst_Assert">
  <properties>
    <property value="@INSERT_QT_VERSION_HERE@" name="QTestVersion"/>
    <property value="@INSERT_QT_VERSION_HERE@" name="QtVersion"/>
  </properties>
  <testcase result="pass" name="initTestCase"/>
  <testcase result="pass" name="testNumber1"/>
  <testcase result="fail" name="testNumber2">
    <!-- message="ASSERT: &quot;false&quot; in file /local/user_builds/qt/4.6/tests/auto/selftests/assert/tst_assert.cpp, line 62" type="qfatal" -->
    <failure message="Received a fatal error." result="fail"/>
  </testcase>
  <system-err>
<![CDATA[ASSERT: "false" in file /local/user_builds/qt/4.6/tests/auto/selftests/assert/tst_assert.cpp, line 62]]>
  </system-err>
</testsuite>
